### ISSUE TITLE
Array of Uuid Values

### ISSUE THREAD

**Issue by bfrog** [sfackler/rust-postgres-array#6]
Seemingly this does not currently support an array of Uuid values is that correct?

**Comment by sfackler** [comment]
It should support it just fine - support is generic over Arrays of all things implementing `ToSql` and `FromSql`.

**Comment by bfrog** [comment]
Hmmm... What about refs to things?

**Comment by sfackler** [comment]
What are you specifically trying to do?

**Comment by bfrog** [comment]
``` sh
src/mymod.rs:94:20: 94:31 error: the trait `postgres::types::ToSql` is not implemented for the type `collections::vec::Vec<&uuid::Uuid>` [E0277]
src/mymod.rs:94     stmt.execute(&[&uuids]).unwrap();
```

When I have essentially the below snippet

``` rust
let uuids : Vec<&Uuid> = myobjects.map(|obj| &obj.uuid).collect();
conn.query("select * from mythings where uuid = any($1)", &[&uuids]).unwrap()
```

**Comment by sfackler** [comment]
Ah gotcha. You can't currently do that, your best bet would be to change that to `map(|obj| obj.uuid.clone()`. It seems reasonable to add an `impl<'a, T: ToSql> ToSql for &'a T` to rust-postgres which would let your original thing work though.

**Comment by bfrog** [comment]
that would be pretty nice, perhaps I can get a PR put together for that, seems easy enough

**Comment by bfrog** [comment]
Actually I get a similiar error for Vec<Uuid> as well :(

``` sh
src/mymod.rs:94:20: 94:31 error: the trait `postgres::types::ToSql` is not implemented for the type `collections::vec::Vec<uuid::Uuid>` [E0277]
src/mymod.rs:94     stmt.execute(&[&deal_uuids]).unwrap();
```

Do I need to have some use statements for this work?

**Comment by sfackler** [comment]
It is correct that `Vec<T>` does not implement `ToSql`. The `Array` type defined in this repo does, however: http://sfackler.github.io/rust-postgres-array/doc/v0.5.2/postgres_array/struct.Array.html

**Comment by sfackler** [comment]
The implementation for `&T` already exists actually: https://github.com/sfackler/rust-postgres/blob/master/src/types/mod.rs#L828-L843

**Comment by bfrog** [comment]
Ahhh so I just need to use that, will try in a few. I expect that was the problem all along
